### ISSUE TITLE
quote unrecognized in head-tail operator

### ISSUE THREAD

**Issue by lutzhamel** [lutzhamel/asteroid#14]
```
let dog = Dog(("name",'name),
               ("tricks",["roll over"|'_]),
               '_).

```
The quote in the head-tail operator leads to an error.

**Comment by TimColaneri** [comment]
An in-depth analysis of this situation revealed that we are getting the correct behavior from the interpreter here. Consider the following...

A HEAD-TAIL constructor can be interpreted through two different views. One view is to see a HEAD-TAIL as a pattern, the other is to see a HEAD-TAIL as a value.There is nothing wrong with using a QUOTE inside of HEAD-TAIL patterns when we view HEAD-TAILs as a pattern. 

Consider that the following program runs fine and is interpreted correctly by the Asteroid interpreter...
```
----------------------------------------
-- a simple program to test
----------------------------------------
----------------------------------------
load system "io".
load system "util".
----------------------------------------
----------------------------------------
function foo
  with [ x | '_ | '_ ] do
    return x.
  end.

let value = foo( [11,2,3,4,5] ).

assert(value == 11).
assert( [1,2,3,4] is [x | '_ ] ).
assert(["roll over","string","another_string"] is ["roll over"|'_]).
```

The problem only arises when we view a HEAD-TAIL constructor as a value, like in the following program...

```
----------------------------------------
-- a simple program to test
----------------------------------------
----------------------------------------
load system "io".
load system "util".

let l = [1|'[2,3]].

println l.
```

The above code generates an error `unsuported tail type quote in head-tail operator` . This is correct because the head-tail operator expects a value here but is handed a term structure.  Since it is a term structure we cannot type check it and make sure that it is a list.  This immediately changes when we evaluate the term structure, shown below...

```
load system "io".

let l = [1|eval('[2,3])].
println l.
```

This program works because we are converting the term structure into a value that can be type checked and therefore we can make sure that it is indeed a list.
