### ISSUE TITLE
repeated variable names in a pattern

### ISSUE THREAD

**Issue by lutzhamel** [lutzhamel/asteroid#27]
Repeated variable names in a pattern should express a constraint in that the pattern should only match if both variables instances match the same term.  Consider:
```
load "io".

let (x,x) = (1,2).
println x.
```
semantically this equivalent to the code
```
load "io".

let (x,y) %if x==y = (1,2).
println x.
```
and should fail.  However, currently the pattern with the two variables instances of the same name succeeds where the second instance match silently overwrites the first and prints out
```
2
```

**Comment by TimColaneri** [comment]
Repeated variable names within a pattern are called non-linear patterns.

Non-linear patterns are not supported by many languages similar to Asteroid due to the ambiguities that arise when using them. Consider the following program...
```
load system "io".

let a = [1,2,3].
let b = [1,2,3].

let (x,x) = (a,b).

let x @1 = 0.  -- which object is being updated here? Ambiguity!

println a.
println b.
```

The statement `let (x,x) = (a,b)`  introduces an ambiguity: after the pattern match, which object does the variable x refer to?

Due to the ambiguities introduced by non-linear patterns, it is the current behavior of the Asteroid interpreter to generate an error when encountering a non-linear pattern.

The error message generated informs the user that a non-linear pattern was found and tells the user the name of the repeated variable.
