### ISSUE TITLE
non-linear pattern detector misinterprets conditional patterns

### ISSUE THREAD

**Issue by lutzhamel** [lutzhamel/asteroid#78]
The non-linear pattern detector throws an error on this first-class pattern,
```
let POS_INT = pattern with (p:%integer) %if p > 0.
```

**Comment by lutzhamel** [comment]
@TimColaneri Here is a program that generates an error,
```
let POS_INT = pattern with (p:%integer) %if p > 0.

function f with (x:*POS_INT,y:*POS_INT) do
  return x+y.
end

let w = f(1,2).
```
Houston, we have a problem, the non-linear pattern checker disables repeated use of first-class patterns...

**Comment by TimColaneri** [comment]
By dereferencing the first-class patterns found in the above program, the nature of the problem becomes more clear...

```
let POS_INT = pattern with (p:%integer) %if p > 0.

function f with (x:( (p:%integer) %if p > 0) ,y:( (p:%integer) %if p > 0) ) do
  return x+y.
end

let w = f(1,2).
```
Repeated use of a first-class pattern* within another pattern creates a non-linear pattern situation by introducing the same variable name multiple times. Above, we can observe that the variable p will be assigned in both of the places where the POS_INT first-class pattern was previously located.

It has been determined that the best method of moving forward is by introducing the new constraint-only pattern match ability to the Asteroid Programming Language. A constraint-only pattern match will be distinguished through the use of "constraint brackets", which will be designated by the %[ and ]% symbols. Should a pattern be found within these constraint-only brackets, the pattern match that follows will only assert that the structure/properties of the term match the pattern, no declarations will be made. Therefor, constraint-only patterns will never introduce a non-linear pattern situation.

Below are two examples of how constraint-only pattern matching should work:
```
-- the POS_INT pattern is just a constraint, no unifiers are exported.
let POS_INT = pattern with %[(p:%integer) %if p > 0]%.

function f with (x:*POS_INT,y:*POS_INT) do
  return x+y.
end

function g with p:*POS_INT do
  return 2*p.
end

assert (f(1,2) == 3).
assert (g(1) == 2).
```
```
let POS_INT = pattern with (p:%integer) %if p > 0.

-- using the POS_INT pattern as a constraint not generating any unifiers
function f with (x:%[*POS_INT]%,y:%[*POS_INT]%) do
  return x+y.
end

-- using the POS_INT pattern in the traditional sense
function g with *POS_INT do
  return 2*p.
end

assert (f(1,2) == 3).
assert (g(1) == 2).
```
Additionally, because declarations are not made during a constraint-only pattern match, the following program should generate an error:
```
-- the POS_INT pattern is just a constraint, no unifiers are exported.
let POS_INT = pattern with %[(p:%integer) %if p > 0]%.


function g with *POS_INT do
  return 2*p. -- error: no unifier for 'p'
end

assert (g(1) == 2).
```
As such, constraint-only patterns can not be used as constructors.

During this evaluation, it was also determined that all `constraint pattern` matches should be consistent and should not be able to be used as constructors. This implies that the following three programs will all generate errors:
```
let x = %[ 1 ]%.
```
```
let x = 1:%integer.
```
```
let x = 1 %if true.
```

*That has named variables(not only wildcards)

**Comment by lutzhamel** [comment]
@TimColaneri should we close this issue?

**Comment by TimColaneri** [comment]
Yes!

This issue is now resolved.

Closing as the above logic, which was implemented into branch 'issue-78', has been merged into master.
