### ISSUE TITLE
Problematic binding in functions.

### ISSUE THREAD

**Issue by olwmc** [lutzhamel/asteroid#80]
This problem is difficult to explain, so I'll give an example.

Consider:
```
load "io".


function foo
    with (bar:%string) do
        return 0.
    orwith (baz:%integer) do
        println("Still " + bar).
	end


foo("[This]").
foo(1).
```

Surely, you would think, this program doesn't work, but it does. `bar` stays in scope after the first call.

This program prints out: `Still [This]`.

**Comment by olwmc** [comment]
So I believe this is happening because of this section in `handle_call` in `asteroid_walk.py`

```
    for body in body_list_val:

        (BODY,
         (PATTERN, p),
         (STMT_LIST, stmts)) = body

        try:
            unifiers = unify(actual_val_args, p)
            unified = True
        except PatternMatchFailed:
            unifiers = []
            unified = False

        if unified:
            break
```

As we can see, each pattern and arg attempt to be unified. This, in turn, has the side effect of changing the symbol table because we are actually carrying out the unification in the event of a matched pattern.

**Comment by lutzhamel** [comment]
@olwmc @TimColaneri @arielfff I'm taking this one on...I have a hunch of what might be going on.

**Comment by lutzhamel** [comment]
Fixed!!  Asteroid now rejects the program above as it should. The problem was that the symbol table was unaware of the difference between computing a closure and copying the configuration of the symtab.  This has now been cleaned up. Note: when computing a closure you need to make a shallow copy of the symtab, when copying the configuration then we only move around object references.
